name: build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set release version
      id: set_version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Print release version
      run: echo "Release version is $RELEASE_VERSION"

    - name: Docker login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Docker build release
      run: docker build . -f ./Dockerfile -t haniffalab/adifa:$RELEASE_VERSION

    - name: Docker push release
      run: docker push haniffalab/adifa:$RELEASE_VERSION